services:
  - type: web
    name: article-app-backend
    env: node
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: article-db
          property: connectionString
      - key: NEWS_API_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false

databases:
  - name: article-db
    databaseName: article_db
    user: article_user 